### ISSUE TITLE
[tailscale-subnet-router] - Role and env vars issues

### ISSUE THREAD

**Issue by nicovak** [gtaylor/helm-charts#1]
Hello and thank you for the chart 👍 

Using `ghcr.io/tailscale/tailscale:latest`

It looks like the role is not set up correctly. The pod is trying to perform actions on `tailscale` secret.

```bash
# With default rule
...
GotCommandMsg: loading requested state: backend prefs: store.ReadState("_daemon"): secrets "tailscale" is forbidden: User "system:serviceaccount:tailscale:tailscale-tailscale-subnet-router" cannot get resource "secrets" in API group "" in the namespace "tailscale"
...

# With get rule
...
GotCommandMsg: initMachineKeyLocked: secrets "tailscale" is forbidden: User "system:serviceaccount:tailscale:tailscale-tailscale-subnet-router" cannot update resource "secrets" in API group "" in the namespace "tailscale"
...

# With update rule It's working
```

In my case, I had to add  `"get"` and `"update"` to the first rule.

```yaml
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    # Create can not be restricted to a resource name.
    verbs: ["create", "get", "update"]
```

Also, working env vars looks like

```bash
TS_KUBE_SECRET
TS_USERSPACE
AUTH_KEY
TS_ROUTES
```
